### ISSUE TITLE
OpenCL CPU based Apriori  fails on i720 on Mac.

### ISSUE THREAD

**Issue by Dzess** [Dzess/DMARF#1]
#### Synopsis

Algorithm 4 with OpenCL on CPU support mining has issue with with working on some data.
#### Invocation

``` bash
$ time java -Xmx1024m -jar target/core-0.0.1-SNAPSHOT-exe.jar
accidents.dat out 80 80 4 
```
#### Stacktrace

``` java
~/code/studies/dbdw/data/accidents.dat out 80 80 4 
Exception in thread "main" org.jocl.CLException: CL_INVALID_WORK_GROUP_SIZE
 at org.jocl.CL.checkResult(CL.java:562)
 at org.jocl.CL.clEnqueueNDRangeKernel(CL.java:15030)
 at org.put.hd.dmarf.algorithms.apriori.binary.JOCLSetsEngine.getSupport(JOCLSetsEngine.java:360)
 at org.put.hd.dmarf.algorithms.apriori.binary.JOCLSetsEngine.verifyCandidatesInData(JOCLSetsEngine.java:112)
 at org.put.hd.dmarf.algorithms.apriori.binary.InjectableSetsEngine.verifyCandidatesInData(InjectableSetsEngine.java:53)
 at org.put.hd.dmarf.algorithms.apriori.binary.BinaryApriori.startSetGeneration(BinaryApriori.java:104)
 at org.put.hd.dmarf.algorithms.AlgorithmBase.start(AlgorithmBase.java:47)
 at org.put.hd.dmarf.App.main(App.java:57)
```

**Comment by ankhazam** [comment]
Please provide us with the output of JoclDeviceQuery test.

**Comment by doriath** [comment]
Number of platforms: 1
Number of devices in platform Apple: 2
--- Info for device GeForce GT 330M: ---
CL_DEVICE_NAME:             GeForce GT 330M
CL_DEVICE_VENDOR:           NVIDIA
CL_DRIVER_VERSION:          CLH 1.0
CL_DEVICE_TYPE:             CL_DEVICE_TYPE_GPU
CL_DEVICE_MAX_COMPUTE_UNITS:        6
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_ITEM_SIZES:      0 / 0 / 0 
CL_DEVICE_MAX_WORK_GROUP_SIZE:      512
CL_DEVICE_MAX_CLOCK_FREQUENCY:      1100 MHz
CL_DEVICE_ADDRESS_BITS:         32
CL_DEVICE_MAX_MEM_ALLOC_SIZE:       128 MByte
CL_DEVICE_GLOBAL_MEM_SIZE:      512 MByte
CL_DEVICE_ERROR_CORRECTION_SUPPORT: no
CL_DEVICE_LOCAL_MEM_TYPE:       local
CL_DEVICE_LOCAL_MEM_SIZE:       16 KByte
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 64 KByte
CL_DEVICE_QUEUE_PROPERTIES:     CL_QUEUE_PROFILING_ENABLE
CL_DEVICE_IMAGE_SUPPORT:        1
CL_DEVICE_MAX_READ_IMAGE_ARGS:      128
CL_DEVICE_MAX_WRITE_IMAGE_ARGS:     8
CL_DEVICE_SINGLE_FP_CONFIG:     CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST 
CL_DEVICE_2D_MAX_WIDTH          0
CL_DEVICE_2D_MAX_HEIGHT         0
CL_DEVICE_3D_MAX_WIDTH          0
CL_DEVICE_3D_MAX_HEIGHT         0
CL_DEVICE_3D_MAX_DEPTH          0
CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>    CHAR 1, SHORT 1, INT 1, LONG 1, FLOAT 1, DOUBLE 0

--- Info for device Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz: ---
CL_DEVICE_NAME:             Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz
CL_DEVICE_VENDOR:           Intel
CL_DRIVER_VERSION:          1.0
CL_DEVICE_TYPE:             CL_DEVICE_TYPE_CPU
CL_DEVICE_MAX_COMPUTE_UNITS:        4
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_ITEM_SIZES:      0 / 0 / 0 
CL_DEVICE_MAX_WORK_GROUP_SIZE:      1
CL_DEVICE_MAX_CLOCK_FREQUENCY:      2800 MHz
CL_DEVICE_ADDRESS_BITS:         64
CL_DEVICE_MAX_MEM_ALLOC_SIZE:       1536 MByte
CL_DEVICE_GLOBAL_MEM_SIZE:      6144 MByte
CL_DEVICE_ERROR_CORRECTION_SUPPORT: no
CL_DEVICE_LOCAL_MEM_TYPE:       global
CL_DEVICE_LOCAL_MEM_SIZE:       16 KByte
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 64 KByte
CL_DEVICE_QUEUE_PROPERTIES:     CL_QUEUE_PROFILING_ENABLE
CL_DEVICE_IMAGE_SUPPORT:        1
CL_DEVICE_MAX_READ_IMAGE_ARGS:      128
CL_DEVICE_MAX_WRITE_IMAGE_ARGS:     8
CL_DEVICE_SINGLE_FP_CONFIG:     CL_FP_DENORM CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST 
CL_DEVICE_2D_MAX_WIDTH          0
CL_DEVICE_2D_MAX_HEIGHT         0
CL_DEVICE_3D_MAX_WIDTH          0
CL_DEVICE_3D_MAX_HEIGHT         0
CL_DEVICE_3D_MAX_DEPTH          0
CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>    CHAR 16, SHORT 8, INT 4, LONG 2, FLOAT 4, DOUBLE 2
